/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FuncionarioRouteImport } from './routes/funcionario'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedEnviarOrcamentoRouteImport } from './routes/_authenticated/enviar-orcamento'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMedicoesRouteImport } from './routes/_authenticated/medicoes'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedPedraRouteImport } from './routes/_authenticated/pedra'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedRomaneiosRouteImport } from './routes/_authenticated/romaneios'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiGenerateObjectRouteImport } from './routes/api/generate-object'
import { Route as ApiGenerateTextureRouteImport } from './routes/api/generate-texture'
import { Route as ApiZapiEnviarPdfRouteImport } from './routes/api/zapi-enviar-pdf'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedConfiguracoesAparenciaRouteImport } from './routes/_authenticated/configuracoes.aparencia'
import { Route as AuthenticatedConfiguracoesBackupsRouteImport } from './routes/_authenticated/configuracoes.backups'
import { Route as AuthenticatedConfiguracoesBiblioteca3dRouteImport } from './routes/_authenticated/configuracoes.biblioteca-3d'
import { Route as AuthenticatedConfiguracoesEmailsAutorizadosRouteImport } from './routes/_authenticated/configuracoes.emails-autorizados'
import { Route as AuthenticatedConfiguracoesTrelloRouteImport } from './routes/_authenticated/configuracoes.trello'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes.usuarios'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro.index'
import { Route as AuthenticatedFinanceiroComissoesRouteImport } from './routes/_authenticated/financeiro.comissoes'
import { Route as AuthenticatedFinanceiroInsightsRouteImport } from './routes/_authenticated/financeiro.insights'
import { Route as AuthenticatedFinanceiroPagarRouteImport } from './routes/_authenticated/financeiro.pagar'
import { Route as AuthenticatedFinanceiroReceberRouteImport } from './routes/_authenticated/financeiro.receber'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated/orcamentos.index'
import { Route as AuthenticatedOrcamentosIdRouteImport } from './routes/_authenticated/orcamentos.$id'
import { Route as AuthenticatedOrcamentosImportarRouteImport } from './routes/_authenticated/orcamentos.importar'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'
import { Route as AuthenticatedPedraThreadIdRouteImport } from './routes/_authenticated/pedra.$threadId'
import { Route as AuthenticatedProducaoIndexRouteImport } from './routes/_authenticated/producao.index'
import { Route as AuthenticatedRelatoriosDiarioRouteImport } from './routes/_authenticated/relatorios.diario'
import { Route as AuthenticatedRelatoriosVendasRouteImport } from './routes/_authenticated/relatorios.vendas'
import { Route as ApiPublicBootstrapPorcelaneRouteImport } from './routes/api/public/bootstrap-porcelane'
import { Route as ApiPublicPixWebhookRouteImport } from './routes/api/public/pix-webhook'
import { Route as AuthenticatedProducaoRelatorioEmployeeIdRouteImport } from './routes/_authenticated/producao.relatorio.$employeeId'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionarioRoute = FuncionarioRouteImport.update({
  id: '/funcionario',
  path: '/funcionario',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnviarOrcamentoRoute =
  AuthenticatedEnviarOrcamentoRouteImport.update({
    id: '/enviar-orcamento',
    path: '/enviar-orcamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicoesRoute = AuthenticatedMedicoesRouteImport.update({
  id: '/medicoes',
  path: '/medicoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedraRoute = AuthenticatedPedraRouteImport.update({
  id: '/pedra',
  path: '/pedra',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRomaneiosRoute = AuthenticatedRomaneiosRouteImport.update({
  id: '/romaneios',
  path: '/romaneios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateObjectRoute = ApiGenerateObjectRouteImport.update({
  id: '/api/generate-object',
  path: '/api/generate-object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateTextureRoute = ApiGenerateTextureRouteImport.update({
  id: '/api/generate-texture',
  path: '/api/generate-texture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZapiEnviarPdfRoute = ApiZapiEnviarPdfRouteImport.update({
  id: '/api/zapi-enviar-pdf',
  path: '/api/zapi-enviar-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConfiguracoesAparenciaRoute =
  AuthenticatedConfiguracoesAparenciaRouteImport.update({
    id: '/aparencia',
    path: '/aparencia',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesBackupsRoute =
  AuthenticatedConfiguracoesBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesBiblioteca3dRoute =
  AuthenticatedConfiguracoesBiblioteca3dRouteImport.update({
    id: '/biblioteca-3d',
    path: '/biblioteca-3d',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesEmailsAutorizadosRoute =
  AuthenticatedConfiguracoesEmailsAutorizadosRouteImport.update({
    id: '/emails-autorizados',
    path: '/emails-autorizados',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesTrelloRoute =
  AuthenticatedConfiguracoesTrelloRouteImport.update({
    id: '/trello',
    path: '/trello',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroComissoesRoute =
  AuthenticatedFinanceiroComissoesRouteImport.update({
    id: '/comissoes',
    path: '/comissoes',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroInsightsRoute =
  AuthenticatedFinanceiroInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroPagarRoute =
  AuthenticatedFinanceiroPagarRouteImport.update({
    id: '/pagar',
    path: '/pagar',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroReceberRoute =
  AuthenticatedFinanceiroReceberRouteImport.update({
    id: '/receber',
    path: '/receber',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosIdRoute =
  AuthenticatedOrcamentosIdRouteImport.update({
    id: '/orcamentos/$id',
    path: '/orcamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosImportarRoute =
  AuthenticatedOrcamentosImportarRouteImport.update({
    id: '/orcamentos/importar',
    path: '/orcamentos/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedraThreadIdRoute =
  AuthenticatedPedraThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedPedraRoute,
  } as any)
const AuthenticatedProducaoIndexRoute =
  AuthenticatedProducaoIndexRouteImport.update({
    id: '/producao/',
    path: '/producao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosDiarioRoute =
  AuthenticatedRelatoriosDiarioRouteImport.update({
    id: '/relatorios/diario',
    path: '/relatorios/diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosVendasRoute =
  AuthenticatedRelatoriosVendasRouteImport.update({
    id: '/relatorios/vendas',
    path: '/relatorios/vendas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBootstrapPorcelaneRoute =
  ApiPublicBootstrapPorcelaneRouteImport.update({
    id: '/api/public/bootstrap-porcelane',
    path: '/api/public/bootstrap-porcelane',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPixWebhookRoute = ApiPublicPixWebhookRouteImport.update({
  id: '/api/public/pix-webhook',
  path: '/api/public/pix-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProducaoRelatorioEmployeeIdRoute =
  AuthenticatedProducaoRelatorioEmployeeIdRouteImport.update({
    id: '/producao/relatorio/$employeeId',
    path: '/producao/relatorio/$employeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/funcionario': typeof FuncionarioRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/enviar-orcamento': typeof AuthenticatedEnviarOrcamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/marketing': typeof AuthenticatedMarketingRoute
  '/medicoes': typeof AuthenticatedMedicoesRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/pedra': typeof AuthenticatedPedraRouteWithChildren
  '/rh': typeof AuthenticatedRhRoute
  '/romaneios': typeof AuthenticatedRomaneiosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-object': typeof ApiGenerateObjectRoute
  '/api/generate-texture': typeof ApiGenerateTextureRoute
  '/api/zapi-enviar-pdf': typeof ApiZapiEnviarPdfRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/configuracoes/aparencia': typeof AuthenticatedConfiguracoesAparenciaRoute
  '/configuracoes/backups': typeof AuthenticatedConfiguracoesBackupsRoute
  '/configuracoes/biblioteca-3d': typeof AuthenticatedConfiguracoesBiblioteca3dRoute
  '/configuracoes/emails-autorizados': typeof AuthenticatedConfiguracoesEmailsAutorizadosRoute
  '/configuracoes/trello': typeof AuthenticatedConfiguracoesTrelloRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/financeiro/comissoes': typeof AuthenticatedFinanceiroComissoesRoute
  '/financeiro/insights': typeof AuthenticatedFinanceiroInsightsRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/orcamentos/importar': typeof AuthenticatedOrcamentosImportarRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedra/$threadId': typeof AuthenticatedPedraThreadIdRoute
  '/relatorios/diario': typeof AuthenticatedRelatoriosDiarioRoute
  '/relatorios/vendas': typeof AuthenticatedRelatoriosVendasRoute
  '/api/public/bootstrap-porcelane': typeof ApiPublicBootstrapPorcelaneRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/producao/': typeof AuthenticatedProducaoIndexRoute
  '/producao/relatorio/$employeeId': typeof AuthenticatedProducaoRelatorioEmployeeIdRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/funcionario': typeof FuncionarioRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/enviar-orcamento': typeof AuthenticatedEnviarOrcamentoRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/medicoes': typeof AuthenticatedMedicoesRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/pedra': typeof AuthenticatedPedraRouteWithChildren
  '/rh': typeof AuthenticatedRhRoute
  '/romaneios': typeof AuthenticatedRomaneiosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-object': typeof ApiGenerateObjectRoute
  '/api/generate-texture': typeof ApiGenerateTextureRoute
  '/api/zapi-enviar-pdf': typeof ApiZapiEnviarPdfRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/configuracoes/aparencia': typeof AuthenticatedConfiguracoesAparenciaRoute
  '/configuracoes/backups': typeof AuthenticatedConfiguracoesBackupsRoute
  '/configuracoes/biblioteca-3d': typeof AuthenticatedConfiguracoesBiblioteca3dRoute
  '/configuracoes/emails-autorizados': typeof AuthenticatedConfiguracoesEmailsAutorizadosRoute
  '/configuracoes/trello': typeof AuthenticatedConfiguracoesTrelloRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/financeiro/comissoes': typeof AuthenticatedFinanceiroComissoesRoute
  '/financeiro/insights': typeof AuthenticatedFinanceiroInsightsRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/orcamentos/importar': typeof AuthenticatedOrcamentosImportarRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedra/$threadId': typeof AuthenticatedPedraThreadIdRoute
  '/relatorios/diario': typeof AuthenticatedRelatoriosDiarioRoute
  '/relatorios/vendas': typeof AuthenticatedRelatoriosVendasRoute
  '/api/public/bootstrap-porcelane': typeof ApiPublicBootstrapPorcelaneRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/producao': typeof AuthenticatedProducaoIndexRoute
  '/producao/relatorio/$employeeId': typeof AuthenticatedProducaoRelatorioEmployeeIdRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/funcionario': typeof FuncionarioRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/enviar-orcamento': typeof AuthenticatedEnviarOrcamentoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/medicoes': typeof AuthenticatedMedicoesRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/pedra': typeof AuthenticatedPedraRouteWithChildren
  '/_authenticated/rh': typeof AuthenticatedRhRoute
  '/_authenticated/romaneios': typeof AuthenticatedRomaneiosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-object': typeof ApiGenerateObjectRoute
  '/api/generate-texture': typeof ApiGenerateTextureRoute
  '/api/zapi-enviar-pdf': typeof ApiZapiEnviarPdfRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/configuracoes/aparencia': typeof AuthenticatedConfiguracoesAparenciaRoute
  '/_authenticated/configuracoes/backups': typeof AuthenticatedConfiguracoesBackupsRoute
  '/_authenticated/configuracoes/biblioteca-3d': typeof AuthenticatedConfiguracoesBiblioteca3dRoute
  '/_authenticated/configuracoes/emails-autorizados': typeof AuthenticatedConfiguracoesEmailsAutorizadosRoute
  '/_authenticated/configuracoes/trello': typeof AuthenticatedConfiguracoesTrelloRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/financeiro/comissoes': typeof AuthenticatedFinanceiroComissoesRoute
  '/_authenticated/financeiro/insights': typeof AuthenticatedFinanceiroInsightsRoute
  '/_authenticated/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/_authenticated/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/_authenticated/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/_authenticated/orcamentos/importar': typeof AuthenticatedOrcamentosImportarRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/pedra/$threadId': typeof AuthenticatedPedraThreadIdRoute
  '/_authenticated/relatorios/diario': typeof AuthenticatedRelatoriosDiarioRoute
  '/_authenticated/relatorios/vendas': typeof AuthenticatedRelatoriosVendasRoute
  '/api/public/bootstrap-porcelane': typeof ApiPublicBootstrapPorcelaneRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/producao/': typeof AuthenticatedProducaoIndexRoute
  '/_authenticated/producao/relatorio/$employeeId': typeof AuthenticatedProducaoRelatorioEmployeeIdRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/funcionario'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clientes'
    | '/configuracoes'
    | '/enviar-orcamento'
    | '/financeiro'
    | '/marketing'
    | '/medicoes'
    | '/minha-conta'
    | '/pedra'
    | '/rh'
    | '/romaneios'
    | '/api/chat'
    | '/api/generate-object'
    | '/api/generate-texture'
    | '/api/zapi-enviar-pdf'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/configuracoes/aparencia'
    | '/configuracoes/backups'
    | '/configuracoes/biblioteca-3d'
    | '/configuracoes/emails-autorizados'
    | '/configuracoes/trello'
    | '/configuracoes/usuarios'
    | '/financeiro/comissoes'
    | '/financeiro/insights'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/orcamentos/$id'
    | '/orcamentos/importar'
    | '/pedidos/$id'
    | '/pedra/$threadId'
    | '/relatorios/diario'
    | '/relatorios/vendas'
    | '/api/public/bootstrap-porcelane'
    | '/api/public/pix-webhook'
    | '/financeiro/'
    | '/orcamentos/'
    | '/pedidos/'
    | '/producao/'
    | '/producao/relatorio/$employeeId'
    | '/api/public/hooks/daily-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/funcionario'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clientes'
    | '/configuracoes'
    | '/enviar-orcamento'
    | '/marketing'
    | '/medicoes'
    | '/minha-conta'
    | '/pedra'
    | '/rh'
    | '/romaneios'
    | '/api/chat'
    | '/api/generate-object'
    | '/api/generate-texture'
    | '/api/zapi-enviar-pdf'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/configuracoes/aparencia'
    | '/configuracoes/backups'
    | '/configuracoes/biblioteca-3d'
    | '/configuracoes/emails-autorizados'
    | '/configuracoes/trello'
    | '/configuracoes/usuarios'
    | '/financeiro/comissoes'
    | '/financeiro/insights'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/orcamentos/$id'
    | '/orcamentos/importar'
    | '/pedidos/$id'
    | '/pedra/$threadId'
    | '/relatorios/diario'
    | '/relatorios/vendas'
    | '/api/public/bootstrap-porcelane'
    | '/api/public/pix-webhook'
    | '/financeiro'
    | '/orcamentos'
    | '/pedidos'
    | '/producao'
    | '/producao/relatorio/$employeeId'
    | '/api/public/hooks/daily-backup'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/funcionario'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/enviar-orcamento'
    | '/_authenticated/financeiro'
    | '/_authenticated/marketing'
    | '/_authenticated/medicoes'
    | '/_authenticated/minha-conta'
    | '/_authenticated/pedra'
    | '/_authenticated/rh'
    | '/_authenticated/romaneios'
    | '/api/chat'
    | '/api/generate-object'
    | '/api/generate-texture'
    | '/api/zapi-enviar-pdf'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/configuracoes/aparencia'
    | '/_authenticated/configuracoes/backups'
    | '/_authenticated/configuracoes/biblioteca-3d'
    | '/_authenticated/configuracoes/emails-autorizados'
    | '/_authenticated/configuracoes/trello'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/financeiro/comissoes'
    | '/_authenticated/financeiro/insights'
    | '/_authenticated/financeiro/pagar'
    | '/_authenticated/financeiro/receber'
    | '/_authenticated/orcamentos/$id'
    | '/_authenticated/orcamentos/importar'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/pedra/$threadId'
    | '/_authenticated/relatorios/diario'
    | '/_authenticated/relatorios/vendas'
    | '/api/public/bootstrap-porcelane'
    | '/api/public/pix-webhook'
    | '/_authenticated/financeiro/'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/pedidos/'
    | '/_authenticated/producao/'
    | '/_authenticated/producao/relatorio/$employeeId'
    | '/api/public/hooks/daily-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FuncionarioRoute: typeof FuncionarioRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateObjectRoute: typeof ApiGenerateObjectRoute
  ApiGenerateTextureRoute: typeof ApiGenerateTextureRoute
  ApiZapiEnviarPdfRoute: typeof ApiZapiEnviarPdfRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBootstrapPorcelaneRoute: typeof ApiPublicBootstrapPorcelaneRoute
  ApiPublicPixWebhookRoute: typeof ApiPublicPixWebhookRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionario': {
      id: '/funcionario'
      path: '/funcionario'
      fullPath: '/funcionario'
      preLoaderRoute: typeof FuncionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enviar-orcamento': {
      id: '/_authenticated/enviar-orcamento'
      path: '/enviar-orcamento'
      fullPath: '/enviar-orcamento'
      preLoaderRoute: typeof AuthenticatedEnviarOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicoes': {
      id: '/_authenticated/medicoes'
      path: '/medicoes'
      fullPath: '/medicoes'
      preLoaderRoute: typeof AuthenticatedMedicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedra': {
      id: '/_authenticated/pedra'
      path: '/pedra'
      fullPath: '/pedra'
      preLoaderRoute: typeof AuthenticatedPedraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/romaneios': {
      id: '/_authenticated/romaneios'
      path: '/romaneios'
      fullPath: '/romaneios'
      preLoaderRoute: typeof AuthenticatedRomaneiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-object': {
      id: '/api/generate-object'
      path: '/api/generate-object'
      fullPath: '/api/generate-object'
      preLoaderRoute: typeof ApiGenerateObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-texture': {
      id: '/api/generate-texture'
      path: '/api/generate-texture'
      fullPath: '/api/generate-texture'
      preLoaderRoute: typeof ApiGenerateTextureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zapi-enviar-pdf': {
      id: '/api/zapi-enviar-pdf'
      path: '/api/zapi-enviar-pdf'
      fullPath: '/api/zapi-enviar-pdf'
      preLoaderRoute: typeof ApiZapiEnviarPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes/aparencia': {
      id: '/_authenticated/configuracoes/aparencia'
      path: '/aparencia'
      fullPath: '/configuracoes/aparencia'
      preLoaderRoute: typeof AuthenticatedConfiguracoesAparenciaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/backups': {
      id: '/_authenticated/configuracoes/backups'
      path: '/backups'
      fullPath: '/configuracoes/backups'
      preLoaderRoute: typeof AuthenticatedConfiguracoesBackupsRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/biblioteca-3d': {
      id: '/_authenticated/configuracoes/biblioteca-3d'
      path: '/biblioteca-3d'
      fullPath: '/configuracoes/biblioteca-3d'
      preLoaderRoute: typeof AuthenticatedConfiguracoesBiblioteca3dRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/emails-autorizados': {
      id: '/_authenticated/configuracoes/emails-autorizados'
      path: '/emails-autorizados'
      fullPath: '/configuracoes/emails-autorizados'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEmailsAutorizadosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/trello': {
      id: '/_authenticated/configuracoes/trello'
      path: '/trello'
      fullPath: '/configuracoes/trello'
      preLoaderRoute: typeof AuthenticatedConfiguracoesTrelloRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/comissoes': {
      id: '/_authenticated/financeiro/comissoes'
      path: '/comissoes'
      fullPath: '/financeiro/comissoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroComissoesRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/insights': {
      id: '/_authenticated/financeiro/insights'
      path: '/insights'
      fullPath: '/financeiro/insights'
      preLoaderRoute: typeof AuthenticatedFinanceiroInsightsRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/pagar': {
      id: '/_authenticated/financeiro/pagar'
      path: '/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroPagarRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/receber': {
      id: '/_authenticated/financeiro/receber'
      path: '/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroReceberRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/$id': {
      id: '/_authenticated/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/importar': {
      id: '/_authenticated/orcamentos/importar'
      path: '/orcamentos/importar'
      fullPath: '/orcamentos/importar'
      preLoaderRoute: typeof AuthenticatedOrcamentosImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedra/$threadId': {
      id: '/_authenticated/pedra/$threadId'
      path: '/$threadId'
      fullPath: '/pedra/$threadId'
      preLoaderRoute: typeof AuthenticatedPedraThreadIdRouteImport
      parentRoute: typeof AuthenticatedPedraRoute
    }
    '/_authenticated/producao/': {
      id: '/_authenticated/producao/'
      path: '/producao'
      fullPath: '/producao/'
      preLoaderRoute: typeof AuthenticatedProducaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/diario': {
      id: '/_authenticated/relatorios/diario'
      path: '/relatorios/diario'
      fullPath: '/relatorios/diario'
      preLoaderRoute: typeof AuthenticatedRelatoriosDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/vendas': {
      id: '/_authenticated/relatorios/vendas'
      path: '/relatorios/vendas'
      fullPath: '/relatorios/vendas'
      preLoaderRoute: typeof AuthenticatedRelatoriosVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-porcelane': {
      id: '/api/public/bootstrap-porcelane'
      path: '/api/public/bootstrap-porcelane'
      fullPath: '/api/public/bootstrap-porcelane'
      preLoaderRoute: typeof ApiPublicBootstrapPorcelaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix-webhook': {
      id: '/api/public/pix-webhook'
      path: '/api/public/pix-webhook'
      fullPath: '/api/public/pix-webhook'
      preLoaderRoute: typeof ApiPublicPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/producao/relatorio/$employeeId': {
      id: '/_authenticated/producao/relatorio/$employeeId'
      path: '/producao/relatorio/$employeeId'
      fullPath: '/producao/relatorio/$employeeId'
      preLoaderRoute: typeof AuthenticatedProducaoRelatorioEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesAparenciaRoute: typeof AuthenticatedConfiguracoesAparenciaRoute
  AuthenticatedConfiguracoesBackupsRoute: typeof AuthenticatedConfiguracoesBackupsRoute
  AuthenticatedConfiguracoesBiblioteca3dRoute: typeof AuthenticatedConfiguracoesBiblioteca3dRoute
  AuthenticatedConfiguracoesEmailsAutorizadosRoute: typeof AuthenticatedConfiguracoesEmailsAutorizadosRoute
  AuthenticatedConfiguracoesTrelloRoute: typeof AuthenticatedConfiguracoesTrelloRoute
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesAparenciaRoute:
      AuthenticatedConfiguracoesAparenciaRoute,
    AuthenticatedConfiguracoesBackupsRoute:
      AuthenticatedConfiguracoesBackupsRoute,
    AuthenticatedConfiguracoesBiblioteca3dRoute:
      AuthenticatedConfiguracoesBiblioteca3dRoute,
    AuthenticatedConfiguracoesEmailsAutorizadosRoute:
      AuthenticatedConfiguracoesEmailsAutorizadosRoute,
    AuthenticatedConfiguracoesTrelloRoute:
      AuthenticatedConfiguracoesTrelloRoute,
    AuthenticatedConfiguracoesUsuariosRoute:
      AuthenticatedConfiguracoesUsuariosRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroComissoesRoute: typeof AuthenticatedFinanceiroComissoesRoute
  AuthenticatedFinanceiroInsightsRoute: typeof AuthenticatedFinanceiroInsightsRoute
  AuthenticatedFinanceiroPagarRoute: typeof AuthenticatedFinanceiroPagarRoute
  AuthenticatedFinanceiroReceberRoute: typeof AuthenticatedFinanceiroReceberRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroComissoesRoute:
      AuthenticatedFinanceiroComissoesRoute,
    AuthenticatedFinanceiroInsightsRoute: AuthenticatedFinanceiroInsightsRoute,
    AuthenticatedFinanceiroPagarRoute: AuthenticatedFinanceiroPagarRoute,
    AuthenticatedFinanceiroReceberRoute: AuthenticatedFinanceiroReceberRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedPedraRouteChildren {
  AuthenticatedPedraThreadIdRoute: typeof AuthenticatedPedraThreadIdRoute
}

const AuthenticatedPedraRouteChildren: AuthenticatedPedraRouteChildren = {
  AuthenticatedPedraThreadIdRoute: AuthenticatedPedraThreadIdRoute,
}

const AuthenticatedPedraRouteWithChildren =
  AuthenticatedPedraRoute._addFileChildren(AuthenticatedPedraRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedEnviarOrcamentoRoute: typeof AuthenticatedEnviarOrcamentoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMedicoesRoute: typeof AuthenticatedMedicoesRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedPedraRoute: typeof AuthenticatedPedraRouteWithChildren
  AuthenticatedRhRoute: typeof AuthenticatedRhRoute
  AuthenticatedRomaneiosRoute: typeof AuthenticatedRomaneiosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrcamentosIdRoute: typeof AuthenticatedOrcamentosIdRoute
  AuthenticatedOrcamentosImportarRoute: typeof AuthenticatedOrcamentosImportarRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedRelatoriosDiarioRoute: typeof AuthenticatedRelatoriosDiarioRoute
  AuthenticatedRelatoriosVendasRoute: typeof AuthenticatedRelatoriosVendasRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedProducaoIndexRoute: typeof AuthenticatedProducaoIndexRoute
  AuthenticatedProducaoRelatorioEmployeeIdRoute: typeof AuthenticatedProducaoRelatorioEmployeeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedEnviarOrcamentoRoute: AuthenticatedEnviarOrcamentoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMedicoesRoute: AuthenticatedMedicoesRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedPedraRoute: AuthenticatedPedraRouteWithChildren,
  AuthenticatedRhRoute: AuthenticatedRhRoute,
  AuthenticatedRomaneiosRoute: AuthenticatedRomaneiosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrcamentosIdRoute: AuthenticatedOrcamentosIdRoute,
  AuthenticatedOrcamentosImportarRoute: AuthenticatedOrcamentosImportarRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedRelatoriosDiarioRoute: AuthenticatedRelatoriosDiarioRoute,
  AuthenticatedRelatoriosVendasRoute: AuthenticatedRelatoriosVendasRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedProducaoIndexRoute: AuthenticatedProducaoIndexRoute,
  AuthenticatedProducaoRelatorioEmployeeIdRoute:
    AuthenticatedProducaoRelatorioEmployeeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FuncionarioRoute: FuncionarioRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateObjectRoute: ApiGenerateObjectRoute,
  ApiGenerateTextureRoute: ApiGenerateTextureRoute,
  ApiZapiEnviarPdfRoute: ApiZapiEnviarPdfRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBootstrapPorcelaneRoute: ApiPublicBootstrapPorcelaneRoute,
  ApiPublicPixWebhookRoute: ApiPublicPixWebhookRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
